[package]
name = "nbt"
version = "0.1.0"
edition = "2021"

[[test]]
name = "integration_tests"
path = "tests/mod.rs"

[dependencies]
flate2 = "1.0"
byteorder = "1"
serde = { version = "1", features = ["derive"] }
indexmap = { version = "2.2", features = ["serde"] }
